name: Build JAR and Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package -DskipTests -T 1C --update-snapshots --activate-profiles prod --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -Dmaven.compiler.useIncrementalCompilation=false --projects "rudi-common,rudi-facet,rudi-microservice" --also-make --also-make-dependents 

      # Login à DockerHub (Nécessite de renseigner les secrets DOCKERHUB_USERNAME et DOCKERHUB_TOKEN dans l'interface github)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        id: push-rudi-microservice-acl
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "rudi-microservice-acl:${{github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/') && github.ref || 'latest'}}"
          target: rudi-microservice-aclcl
      - name: Build Docker image
        id: push-rudi-microservice-apigateway
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "rudi-microservice-apigateway:${{github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/') && github.ref || 'latest'}}"
          target: rudi-microservice-apigateway
      - name: Build Docker image
        id: push-rudi-microservice-gateway
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "rudi-microservice-gateway:${{github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/') && github.ref || 'latest'}}"
          target: rudi-microservice-gateway
      - name: Build Docker image
        id: push-rudi-microservice-kalim
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "rudi-microservice-kalim:${{github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/') && github.ref || 'latest'}}"
          target: rudi-microservice-kalim
      - name: Build Docker image
        id: push-rudi-microservice-konsent
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "rudi-microservice-konsent:${{github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/') && github.ref || 'latest'}}"
          target: rudi-microservice-konsent
      - name: Build Docker image
        id: push-rudi-microservice-konsult
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "rudi-microservice-konsult:${{github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/') && github.ref || 'latest'}}"
          target: rudi-microservice-konsult
      - name: Build Docker image
        id: push-rudi-microservice-kos
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "rudi-microservice-kos:${{github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/') && github.ref || 'latest'}}"
          target: rudi-microservice-koscl
      - name: Build Docker image
        id: push-rudi-microservice-projekt
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "rudi-microservice-projekt:${{github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/') && github.ref || 'latest'}}"
          target: rudi-microservice-projekt
      - name: Build Docker image
        id: push-rudi-microservice-registry
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "rudi-microservice-registry:${{github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/') && github.ref || 'latest'}}"
          target: rudi-microservice-registry
      - name: Build Docker image
        id: push-rudi-microservice-selfdata
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "rudi-microservice-selfdata:${{github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/') && github.ref || 'latest'}}"
          target: rudi-microservice-selfdata
      - name: Build Docker image
        id: push-rudi-microservice-strukture
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "rudi-microservice-strukture:${{github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/') && github.ref || 'latest'}}"
          target: rudi-microservice-strukture
      - name: Build Docker image
        id: push-rudi-microservice-template
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "rudi-microservice-template:${{github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/') && github.ref || 'latest'}}"
          target: rudi-microservice-template
